
import type { MenuItem } from '@/types';

export const menuItems: MenuItem[] = [
  {
    id: 1,
    name: 'Classic Burger',
    rate: 9.99,
    category: 'Burgers',
    portion: 'Regular',
    is_active: true,
    available: true,
  },
  {
    id: 2,
    name: 'Cheese Burger',
    rate: 10.99,
    category: 'Burgers',
    portion: 'Regular',
    is_active: true,
    available: true,
  },
  {
    id: 3,
    name: 'Bacon Burger',
    rate: 11.99,
    category: 'Burgers',
    portion: 'Regular',
    is_active: true,
    available: true,
  },
  {
    id: 4,
    name: 'Veggie Burger',
    rate: 9.99,
    category: 'Burgers',
    portion: 'Regular',
    is_active: true,
    available: true,
  },
  {
    id: 5,
    name: 'French Fries',
    rate: 3.99,
    category: 'Sides',
    portion: 'Regular',
    is_active: true,
    available: true,
  },
  {
    id: 6,
    name: 'Onion Rings',
    rate: 4.99,
    category: 'Sides',
    portion: 'Regular',
    is_active: true,
    available: true,
  },
  {
    id: 7,
    name: 'Garden Salad',
    rate: 5.99,
    category: 'Sides',
    portion: 'Regular',
    is_active: true,
    available: true,
  },
  {
    id: 8,
    name: 'Coca-Cola',
    rate: 1.99,
    category: 'Drinks',
    portion: 'Regular',
    is_active: true,
    available: true,
  },
  {
    id: 9,
    name: 'Lemonade',
    rate: 2.49,
    category: 'Drinks',
    portion: 'Regular',
    is_active: true,
    available: true,
  },
   {
    id: 10,
    name: 'Iced Tea',
    rate: 1.99,
    category: 'Drinks',
    portion: 'Regular',
    is_active: true,
    available: true,
  },
];
