import type { MenuItem } from '@/types';

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Classic Burger',
    description: 'A juicy beef patty with lettuce, tomato, and our special sauce.',
    price: 9.99,
    category: 'Burgers',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: '2',
    name: 'Cheese Burger',
    description: 'Our classic burger topped with melted cheddar cheese.',
    price: 10.99,
    category: 'Burgers',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: '3',
    name: 'Bacon Burger',
    description: 'Crispy bacon and our classic burger patty, a perfect match.',
    price: 11.99,
    category: 'Burgers',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: '4',
    name: 'Veggie Burger',
    description: 'A delicious plant-based patty with fresh vegetables.',
    price: 9.99,
    category: 'Burgers',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: '5',
    name: 'French Fries',
    description: 'Golden, crispy, and perfectly salted.',
    price: 3.99,
    category: 'Sides',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: '6',
    name: 'Onion Rings',
    description: 'Battered and fried to a golden brown.',
    price: 4.99,
    category: 'Sides',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: '7',
    name: 'Garden Salad',
    description: 'Fresh greens with a light vinaigrette dressing.',
    price: 5.99,
    category: 'Sides',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: '8',
    name: 'Coca-Cola',
    description: 'Classic and refreshing.',
    price: 1.99,
    category: 'Drinks',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: '9',
    name: 'Lemonade',
    description: 'Freshly squeezed and perfectly sweet.',
    price: 2.49,
    category: 'Drinks',
    imageUrl: 'https://placehold.co/600x400.png',
  },
   {
    id: '10',
    name: 'Iced Tea',
    description: 'Brewed fresh daily.',
    price: 1.99,
    category: 'Drinks',
    imageUrl: 'https://placehold.co/600x400.png',
  },
];
